services:
- type: web
  name: vilt-hjerte-stugas
  env: docker
  plan: standard
  autoDeploy: false
  disk:
    name: wordpress
    mountPath: /var/www/html
    sizeGB: 5
  envVars:
  - key: WORDPRESS_DB_HOST
    fromService:
      name: vilt-hjerte-mysql
      type: pserv
      property: host
  - key: WORDPRESS_DB_NAME
    fromService:
      name: vilt-hjerte-mysql
      type: pserv
      envVarKey: MYSQL_DATABASE
  - key: WORDPRESS_DB_USER
    fromService:
      name: vilt-hjerte-mysql
      type: pserv
      envVarKey: MYSQL_USER
  - key: WORDPRESS_DB_PASSWORD
    fromService:
      name: vilt-hjerte-mysql
      type: pserv
      envVarKey: MYSQL_PASSWORD
- type: pserv
  name: vilt-hjerte-mysql
  repo: https://github.com/render-examples/mysql.git
  env: docker
  plan: standard
  autoDeploy: false
  disk:
    name: vilt-hjerte-mysql
    mountPath: /var/lib/mysql
    sizeGB: 20
  envVars:
  - key: MYSQL_DATABASE
    value: vilt-hjerte-db
  - key: MYSQL_USER
    value: vilt-hjerte-user
  - key: MYSQL_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true
